### ISSUE TITLE
Cannot find MATLAB or Octave instalation

### ISSUE THREAD

**Issue by tonystark12** [mariusmuja/flann#107]
Thanks for the library. Would be a great help for my research. I followed up few issues and was able to solve few problems that I encountered with hdf5, etc. However, am having this issue, and I know this is about adding something to the PATH. Could you please tell me how to add it?

iiith@iiith-N80Vb:~/flann-1.6.11-src/release$ cmake ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.3")
-- Found HDF5: debug;/usr/lib/libhdf5.so;optimized;/usr/lib/libhdf5.so 
-- Found GTest: /usr/lib/libgtest.a 
CMake Error at src/matlab/CMakeLists.txt:71 (message):
  Cannot find MATLAB or Octave instalation.  Make sure that the 'bin'
  directory from the MATLAB instalation or that mkoctfile is in PATH

-- I could not find the latex2html command.
-- Install prefix: /usr/local
-- Build type: RelWithDebInfo
-- Building C bindings: ON
-- Building python bindings: ON
-- Building matlab bindings: ON
-- Using MPI support: OFF
-- Configuring incomplete, errors occurred!

There are different parameters in the end as well, which am not able to understand. Please help me to know if they are right and how to solve the issues so that it would compile without error. Thanks in advance

**Comment by huiminzeng** [comment]
Hi! Why did you close this issue? I just have encountered it as well. Do you know how to solve it? thx

**Comment by xiaoxiaobx** [comment]
Have you solved your problem? I have the same problem. How can I solve it?
Thank you！

**Comment by xiaoxiaobx** [comment]
@tonystark12 ，
Have you solved your problem? I have the same problem. How can I solve it?
Thank you!

**Comment by tonystark12** [comment]
Hey, this was long back during my Masters. I would have to revisit, check on this again. Shall get back to you.

**Comment by yo-mark** [comment]
Hi ,  do you recall how you fixed this ?
