### ISSUE TITLE
is_kdtree_distance restrictions?

### ISSUE THREAD

**Issue by piskvorky** [mariusmuja/flann#143]
Sorry if I missed this in the docs: what properties must a FLANN distance function have, in order to work correctly with autotune & kdtree?

I'm thinking of adding the cosine distance, `1 - xy/|x||y|` (not a metric!), as another type of distance. Implementing the distance itself is fairly trivial, but I'm not sure how to make it play nicely with the rest of FLANN (index types etc).

Is it a `is_vector_space_distance`, a `is_kdtree_distance`?

Cossim is a very popular measure, so I assume there some problem, since it's not in FLANN yet?

**Comment by StevenLOL** [comment]
@piskvorky  thanks for point this out: cossim = 1 - flann_dist / 2
