### ISSUE TITLE
Error when compililing flann_example.cpp

### ISSUE THREAD

**Issue by marco-p** [mariusmuja/flann#16]
Hi, 
Thanks for providing this nice piece of software and being continuously trying to improve it.
I was following the instructions in the manual, and trying to compile flann_example.cpp, but I was not able to do it. 

I tried rebuilding the program and I saw the following message:

-- Could NOT find HDF5  (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
CMake Warning at CMakeLists.txt:64 (message):
  hdf5 library not found, some tests will not be run

-- Could NOT find GTest  (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
CMake Warning at CMakeLists.txt:95 (message):
  gtest library not found, some tests will not be run

is there a way I can fix this and be able to compile flann_example.cpp?
Sincerely,
Marco

**Comment by mruegenberg** [comment]
For others who have installed HDF5, but still get the error:
Note that you have to install the hdf5 CPP library, which might be separate from the normal hdf5 package (e.g on Arch Linux, install `hdf5-cpp-fortran`).
