### ISSUE TITLE
Difference of KDTreeIndexParams vs. KDTreeSingleIndexParams

### ISSUE THREAD

**Issue by enfo** [mariusmuja/flann#187]
Hi, I noticed that an index build with KDTreeIndexParams(1) is a lot faster than an index build with KDTreeSingleIndexParams(). From my understanding, both are using a single KD-Tree. So I was wondering what causes the different runtime. Is KDTreeIndexParams an approximate NN-Search and KDTreeSingleIndexParams an exact search Index, or is there some other difference?

**Comment by ColinDavid** [comment]
Great reply

**Comment by ColinDavid** [comment]
> Yes, that's exactly it. KDTreeIndex performs approximate NN search, while KDTreeSingleIndex performs exact NN search. The KDTreeSingleIndex is efficient for low dimensional data, for high dimensional data an approximate search algorithm such as the KDTreeIndex will be much faster.

great reply!
