### ISSUE TITLE
Data to test FLANN

### ISSUE THREAD

**Issue by tomtran** [mariusmuja/flann#19]
Dear Marius Muja,
I wonder that where I can get data to test FLANN? I have a set of vectors. How can I config them to be input for FLANN?
Thank you!

**Comment by kianakh9090** [comment]
Hi,
I installed the HDF5 package in my documents folder in linux and I verified that it is installed on my system. I enterd "cmake .." to compile flann library on linux but I have errors as following:
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
CMake Warning at CMakeLists.txt:76 (message):
  hdf5 library not found, some tests will not be run


-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Warning at CMakeLists.txt:115 (message):
  gtest library not found, some tests will not be run


-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Could NOT find OpenMP (missing:  OpenMP_CXX_FLAGS) 
CMake Warning at CMakeLists.txt:126 (message):
  OpenMP NOT found


CMake Warning at src/matlab/CMakeLists.txt:79 (message):
  Cannot find MATLAB or Octave instalation.  Make sure that the 'bin'
  directory from the MATLAB instalation or that mkoctfile is in PATH


hdf5 library not found, not compiling flann_example.cpp
-- Install prefix: /usr/local
-- Build type: RelWithDebInfo
-- Building C bindings: ON
-- Building python bindings: ON
-- Building matlab bindings: ON
-- Building CUDA library: OFF
-- Using OpenMP support: ON
-- Using MPI support: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kiana/Documents/flann-1.8.4-src/build

I want to run flann library for knn matching.
