### ISSUE TITLE
matlab problem with nearest_neighbors.cpp

### ISSUE THREAD

**Issue by ehsansadr** [mariusmuja/flann#233]
I am using a library that calls your code. I download Flann from here and installed it successfully without any error on ubuntu and now I am trying to use it in matlab 2012a.
I get below error. I tried to find some answer in other website and they mentioned that the warning is not important. But I haven't solved the problem yet.

Warning: You are using gcc version "4.6.3-1ubuntu5)".  The version
         currently supported with MEX is "4.4.6".
         For a list of currently supported compilers see:
         http://www.mathworks.com/support/compilers/current_release/

-> g++ -c  -I/usr/local/MATLAB/2012a/extern/include -I/usr/local/MATLAB/2012a/simulink/include -DMATLAB_MEX_FILE -ansi -D_GNU_SOURCE -fPIC -fno-omit-frame-pointer -pthread  -DMX_COMPAT_32 -O -DNDEBUG  "nearest_neighbors.cpp"

nearest_neighbors.cpp:35:25: fatal error: flann/flann.h: No such file or directory
compilation terminated.

    mex: compile of ' "nearest_neighbors.cpp"' failed.

Error using mex (line 206)
Unable to complete successfully.

**Comment by Garoe** [comment]
If you are using ubuntu, you can install from the repos with 
1. sudo apt-get install libflann-dev
2. Grab the flann code from github
2. Unzip the code and go to the src/matlab folder
3. Copy the folder into your matlab folder and rename it to flann
4. Open matlab and cd into the flann folder
5. run mex -L/usr/lib -lflann -I/usr/include nearest_neighbors.cpp

**Comment by ehsansadr** [comment]
Thanks a lot for your prompt reply. Unfortunately I don't have access to install packages. But I fixed it and I share it in this link : http://stackoverflow.com/q/29152126/2674061

**Comment by kli-nlpr** [comment]
> If you are using ubuntu, you can install from the repos with
> 
> 1. sudo apt-get install libflann-dev
> 2. Grab the flann code from github
> 3. Unzip the code and go to the src/matlab folder
> 4. Copy the folder into your matlab folder and rename it to flann
> 5. Open matlab and cd into the flann folder
> 6. run mex -L/usr/lib -lflann -I/usr/include nearest_neighbors.cpp

Invalid MEX-file '~/flann/nearest_neighbors.mexa64': dlopen: cannot load
any more object with static TLS.

How to fix this? thanks  @Garoe

**Comment by 98khongmin** [comment]
> If you are using ubuntu, you can install from the repos with
> 
> 1. sudo apt-get install libflann-dev
> 2. Grab the flann code from github
> 3. Unzip the code and go to the src/matlab folder
> 4. Copy the folder into your matlab folder and rename it to flann
> 5. Open matlab and cd into the flann folder
> 6. run mex -L/usr/lib -lflann -I/usr/include nearest_neighbors.cpp

@Era-Dorta  I have been looking all over the place to make this code work, and now it finally works. Thank you so much, good sir.
