### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by V-Tom** [mariusmuja/flann#260]
HI,i am a student from China.
here are some Errors;
[ 12%] Building CXX object src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.o
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘int _flann_add_points(flann_index_t, T*, int, int, float)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:316:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<L2<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:319:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<L1<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:322:54: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<MinkowskiDistance<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                                      ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:325:61: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<HistIntersectionDistance<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                                             ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:328:54: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<HellingerDistance<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                                      ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:331:54: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<ChiSquareDistance<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                                      ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:334:50: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_add_points<KL_Divergence<T>>(index_ptr, points, rows, columns, rebuild_threshold);
                                                  ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘int _flann_remove_point(flann_index_t, unsigned int)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:389:41: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<L2<T>>(index_ptr, point_id);
                                         ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:392:41: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<L1<T>>(index_ptr, point_id);
                                         ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:395:56: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<MinkowskiDistance<T>>(index_ptr, point_id);
                                                        ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:398:63: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<HistIntersectionDistance<T>>(index_ptr, point_id);
                                                               ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:401:56: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<HellingerDistance<T>>(index_ptr, point_id);
                                                        ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:404:56: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<ChiSquareDistance<T>>(index_ptr, point_id);
                                                        ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:407:52: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_remove_point<KL_Divergence<T>>(index_ptr, point_id);
                                                    ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘T* _flann_get_point(flann_index_t, unsigned int)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:461:38: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<L2<T>>(index_ptr, point_id);
                                      ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:464:38: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<L1<T>>(index_ptr, point_id);
                                      ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:467:53: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<MinkowskiDistance<T>>(index_ptr, point_id);
                                                     ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:470:60: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<HistIntersectionDistance<T>>(index_ptr, point_id);
                                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:473:53: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<HellingerDistance<T>>(index_ptr, point_id);
                                                     ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:476:53: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<ChiSquareDistance<T>>(index_ptr, point_id);
                                                     ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:479:49: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_get_point<KL_Divergence<T>>(index_ptr, point_id);
                                                 ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘unsigned int _flann_veclen(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:531:35: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<L2<T>>(index_ptr);
                                   ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:534:35: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<L1<T>>(index_ptr);
                                   ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:537:50: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<MinkowskiDistance<T>>(index_ptr);
                                                  ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:540:57: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<HistIntersectionDistance<T>>(index_ptr);
                                                         ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:543:50: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<HellingerDistance<T>>(index_ptr);
                                                  ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:546:50: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<ChiSquareDistance<T>>(index_ptr);
                                                  ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:549:46: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_veclen<KL_Divergence<T>>(index_ptr);
                                              ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘unsigned int _flann_size(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:601:33: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<L2<T>>(index_ptr);
                                 ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:604:33: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<L1<T>>(index_ptr);
                                 ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:607:48: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<MinkowskiDistance<T>>(index_ptr);
                                                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:610:55: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<HistIntersectionDistance<T>>(index_ptr);
                                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:613:48: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<HellingerDistance<T>>(index_ptr);
                                                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:616:48: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<ChiSquareDistance<T>>(index_ptr);
                                                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:619:44: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_size<KL_Divergence<T>>(index_ptr);
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘int _flann_used_memory(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:671:40: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<L2<T>>(index_ptr);
                                        ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:674:40: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<L1<T>>(index_ptr);
                                        ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:677:55: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<MinkowskiDistance<T>>(index_ptr);
                                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:680:62: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<HistIntersectionDistance<T>>(index_ptr);
                                                              ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:683:55: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<HellingerDistance<T>>(index_ptr);
                                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:686:55: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<ChiSquareDistance<T>>(index_ptr);
                                                       ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:689:51: error: ‘>>’ should be ‘> >’ within a nested template argument list
         return __flann_used_memory<KL_Divergence<T>>(index_ptr);
                                                   ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_add_points(flann_index_t, T*, int, int, float) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:344:88:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:338:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_add_points(flann_index_t, T*, int, int, float) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:354:89:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:338:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_add_points(flann_index_t, T*, int, int, float) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:359:96:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:338:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_add_points(flann_index_t, T*, int, int, float) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:364:86:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:338:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_remove_point(flann_index_t, unsigned int) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:417:58:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:411:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_remove_point(flann_index_t, unsigned int) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:427:59:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:411:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_remove_point(flann_index_t, unsigned int) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:432:66:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:411:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_remove_point(flann_index_t, unsigned int) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:437:56:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:411:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:559:42:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:569:43:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:574:50:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:579:40:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:629:40:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:639:41:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:644:48:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:649:38:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_used_memory(flann_index_t) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:699:47:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:693:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_used_memory(flann_index_t) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:709:48:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:693:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_used_memory(flann_index_t) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:714:55:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:693:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘int _flann_used_memory(flann_index_t) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:719:45:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:693:16: warning: converting to non-pointer type ‘int’ from NULL [-Wconversion-null]
make[2]: *** [src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.o] 错误 1
make[1]: *** [src/cpp/CMakeFiles/flann_s.dir/all] 错误 2
make: *** [all] 错误 2
can you help me to solve it?
Thanks a lot.

**Comment by dm-jrae** [comment]
Apologies, this is due to my commit: https://github.com/mariusmuja/flann/commit/907fec83da777624f836b275ba44b8bbd676c46f
I realize it is not compatible with older C++ versions, I tested this on C++11. I have a fix to those issues in
https://github.com/dm-jrae/flann/commit/07daf8e308988e6d0ee4ebf900d666691fb84f3f
but I have not tried compiling with an older compilation mode yet (I can in a couple of hours). If you are blocked now, could you try cherry-picking this and ping the thread if it alleviates the issue - I will create a pull request asap if so.

**Comment by dm-jrae** [comment]
There is a fix in a pending pull request: https://github.com/mariusmuja/flann/pull/261

**Comment by V-Tom** [comment]
Thanks!
in fact,i am a web Dev.my boss let me to do GCC  compiler C++ in unbuntu
i know about it a little.

this problem is ok
but there are another error in my work

shareduser@vmwareubunt-virtual-machine:/home/beopWeb/flann-master/build$ make 
Scanning dependencies of target flann_s
[ 12%] Building CXX object src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.o
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘int __flann_remove_point(flann_index_t, unsigned int)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:369:44: warning: typedef ‘ElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Distance::ElementType ElementType;
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘typename Distance::ElementType* __flann_get_point(flann_index_t, unsigned int)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:443:44: warning: typedef ‘ElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Distance::ElementType ElementType;
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘unsigned int __flann_veclen(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:514:44: warning: typedef ‘ElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Distance::ElementType ElementType;
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘unsigned int __flann_size(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:584:44: warning: typedef ‘ElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Distance::ElementType ElementType;
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In function ‘int __flann_used_memory(flann_index_t)’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:654:44: warning: typedef ‘ElementType’ locally defined but not used [-Wunused-local-typedefs]
     typedef typename Distance::ElementType ElementType;
                                            ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:559:42:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:569:43:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:574:50:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_veclen(flann_index_t) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:579:40:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:553:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = float; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:629:40:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
         return NULL;
                ^
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = double; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:639:41:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = unsigned char; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:644:48:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp: In instantiation of ‘unsigned int _flann_size(flann_index_t) [with T = int; flann_index_t = void*]’:
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:649:38:   required from here
/home/beopWeb/flann-master/src/cpp/flann/flann.cpp:623:16: warning: converting to non-pointer type ‘unsigned int’ from NULL [-Wconversion-null]

And then it stopped,why?

**Comment by dm-jrae** [comment]
You need to pull the latest changes on master, the pull request that I alluded to (#261) fixed the issue.
