### ISSUE TITLE
Compilation error in Visual Studio 2015

### ISSUE THREAD

**Issue by termi-official** [mariusmuja/flann#278]
Tried to compile on Visual Studio 2015 and got an error: flann:serialization::Serializer<unsigned __int64> redefined in file serialization.h line 112

I fixed it locally by changing the line to:

`#if _MSC_VER < 1800`

Since it is the same problem that occured in VS2013.

Used branch: master
Current commit:  b8a442f

**Comment by aragonsr** [comment]
Where is this line?

**Comment by termi-official** [comment]
[Here](https://github.com/mariusmuja/flann/blob/master/src/cpp/flann/util/serialization.h#L112), sorry.

**Comment by termi-official** [comment]
Fixed with https://github.com/mariusmuja/flann/commit/a7d8b74fc394bb6222f3bfb654c8f178be8a0ee9 .
