### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [mariusmuja/flann#288]
Last release was 1.8.4, which was over 3 years ago. There have been a fair number of changes and enhancements since then. Could we get a new release?

**Comment by tigerfoot** [comment]
:+1:

**Comment by KindDragon** [comment]
@mariusmuja please add at-least special tag for latest commit (1.8.5 ?)

**Comment by mariusmuja** [comment]
Added tag 1.8.5 to latest commit.

**Comment by jakirkham** [comment]
Thanks. Going to go ahead and close this.

**Comment by tigerfoot** [comment]
Would be cool to fix also the README.md ;-)
