### ISSUE TITLE
ImportError: Cannot load dynamic library. Did you compile FLANN?

### ISSUE THREAD

**Issue by pfrcks** [mariusmuja/flann#296]
Hi,

I compiled and built FLANN from src. 
Upon trying to import pyflann, I was getting 
`ImportError: Cannot load dynamic library. Did you compile FLANN?`

I have Anaconda installed on my system.
Upon looking in the code I found that in
`/home/pfrcks/anaconda2/lib/python2.7/site-packages/pyflann-1.6.12-py2.7.egg/pyflann/bindings/flann_ctypes.py`

On line 135, 
`libnames = ['linux/libflann.so']` is given.

However when it installs, all the .so files are not inside an intermediate folder named 'linux'

`cd /home/pfrcks/anaconda2/lib/python2.7/site-packages/pyflann-1.6.12-py2.7.egg/pyflann/bindings/lib/linux/`

`cd: no such file or directory: /home/pfrcks/anaconda2/lib/python2.7/site-packages/pyflann-1.6.12-py2.7.egg/pyflann/bindings/lib/linux/`

I removed linux from the string and now it works fine.
Is this a bug, or something specific to my system?

**Comment by mittalkashish2** [comment]
Hi.
Can you please share how to use [Flann](https://github.com/flann-lib/flann) in a step-by-step manner in Python?

![Screenshot from 2023-04-26 17-15-48](https://user-images.githubusercontent.com/34433967/234565414-923b73d6-dcff-4c5f-9fc5-bc9f4ba60bec.png)
