### ISSUE TITLE
kdtree_index.h - Mistake

### ISSUE THREAD

**Issue by wbrandenburger** [mariusmuja/flann#327]
Hi,

there is a mistake in kdtree_index.h searchlevelExact(...). The computation of new_distsq is not correct! You get not the exact neighbors of a abitrary point when you use this function. When you use knn-search with the  KDtreeSingleIndexParams you get instead the correct neighbors. In this function (searchlevel()) mindistsq is correctly computed!

Greets from Munich

**Comment by wbrandenburger** [comment]
Hi,

in Addition you should use in kdtree_index.h searchLevelExact the variable new_distsq rather than mindist in the if loop when entering another branch.

Greets from Munich

**Comment by mariusmuja** [comment]
The kdtree_index is not an exact search algorithm, it's an approximate search algorithm for high dimensional points. The computation for new_distsq is incorrect in those cases when the same dimension is picked multiple times during a tree construction. 
For high dimensional points, splitting on the same dimension multiple times in the same tree is unlikely, so doing a simpler computation of the partial distance during the tree exploration was something that worked well in practice.

**Comment by mariusmuja** [comment]
> in Addition you should use in kdtree_index.h searchLevelExact the variable new_distsq rather than mindist in the if loop when entering another branch.

`new_distsq` is used when searching the `otherChild` (the one across the cell boundary). `mindist` is used when searching the node on the same side of the cell boundary.

**Comment by wbrandenburger** [comment]
new_distsq is used when searching the otherChild (the one across the cell boundary). mindist is used when searching the node on the same side of the cell boundary.

(searchLevelExact - kdtree_index.h) Thats correct. But the computation of new_distsq is not correct. You get too big values for new_distsq when you add always to mindist the difference between val and node->divval. I think you have to change it.

(searchLevel - kdtree_index.h) The same computation of newdistsq is in searchLevel not correct. But there are less challenges to fix it. You have to add a std::vector (not recommended) or a allocated array, both cause a slowdown in runtime. Not significant but there is a slowdown. As geodesist I want to have almost a good accuracy and I can live with this slowdown. Especially when I set unlimited checks I want to get correct results. You have to imagine that the wrong computation of new_distsq can have huge effects on the result in special cases.

Yes, you are correct, this is an issue that needs fixing.

I implemented a balanced tree (it was a little bit challenging because the implementation tended to loose pointer :)) and I use it instead of DynamicBitsize (i use dynamicBitsize when the number of searched neigbors is more than one eighth of the pointcloudsize). In addition i use a dynamic heapsize. As a result Im incredibly faster. Are you interested in my implementation of the balanced tree?


Im sorry when im annoying you with my stuff?



--
Wolfgang Brandenburger

Mainstraße 15f
85579 Neubiberg
