### ISSUE TITLE
error: calling a __device__ function("CountingRadiusResultSet") from a __host__ function("radiusSearchGpu") is not allowed

### ISSUE THREAD

**Issue by itabhiyanta** [mariusmuja/flann#332]
Hi

I am trying to compile flann for use on a M4000 GPU. I came across some architecture issues but those i fixed then I am seeing these errors

error: calling a __device__ function("CountingRadiusResultSet") from a __host__ function("radiusSearchGpu") is not allowed

and around 48 of them. I read on the forums that you have handled such an issue in a merge. I am compiling with cuda 7.5 and also gcc 5.4. I have tried both with the flann code on github and the version 1.8.4 but to no avail.

Kindly help.
Rohit

**Comment by itabhiyanta** [comment]
apparently using the following flags fixed compilation in the version available on github

CXX_FLAGS = -D__CUDA_PREC_DIV

NVCC_FLAGS = -use_fast_math -D__CUDA_PREC_DIV --gpu-architecture=compute_52 --gpu-code=sm_52,compute_52; -std=c++11; -D_MWAITXINTRIN_H_INCLUDED; -D_FORCE_INLINES; D_STRICT_ANSI

**Comment by Auroratan** [comment]
> apparently using the following flags fixed compilation in the version available on github
> 
> CXX_FLAGS = -D__CUDA_PREC_DIV
> 
> NVCC_FLAGS = -use_fast_math -D__CUDA_PREC_DIV --gpu-architecture=compute_52 --gpu-code=sm_52,compute_52; -std=c++11; -D_MWAITXINTRIN_H_INCLUDED; -D_FORCE_INLINES; D_STRICT_ANSI



> apparently using the following flags fixed compilation in the version available on github
> 
> CXX_FLAGS = -D__CUDA_PREC_DIV
> 
> NVCC_FLAGS = -use_fast_math -D__CUDA_PREC_DIV --gpu-architecture=compute_52 --gpu-code=sm_52,compute_52; -std=c++11; -D_MWAITXINTRIN_H_INCLUDED; -D_FORCE_INLINES; D_STRICT_ANSI

Hello, I'm also experiencing the same problem, according to your method, mine still prompts error！

I have made the following changes：
		set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS}; -use_fast_math -D__CUDA_PREC_DIV -gencode arch=compute_61,code=sm_61;-DVERBOSE; -std=c++11; -D_MWAITXINTRIN_H_INCLUDED; -D_FORCE_INLINES;-D_STRICT_ANSI" )

Can you help me with this?
