### ISSUE TITLE
Attaching metadata to the points in the index

### ISSUE THREAD

**Issue by rodrigob** [mariusmuja/flann#35]
It would be nice if the documentation would suggest a recommended way to attach meta-data to the points (feature vectors) stored in memory. 

I am surprised to see that the data input is handled as a Matrix, had it been a vector of a datatype defined as a Distance:: element, then defining the application specific type (e.g. struct { point_t point; data_t data; } ) and reusing the FLANN distances over "element.point" would have been the way to go.

With the current code base, what is the recommend approach ?

**Comment by 14327319** [comment]
> You can keep an external vector of the same size as the number of rows in
> the points matrix. All the nearest neighbors operations return the indices
> of the nearest neighbors that you can use to index in this vector.
> 
> Marius
> 
> On Wed, Mar 21, 2012 at 11:13 AM, Rodrigo Benenson <
> [reply@reply.github.com](mailto:reply@reply.github.com)
> 
> > wrote:
> > It would be nice if the documentation would suggest a recommended way to
> > attach meta-data to the points (feature vectors) stored in memory.
> > I am surprised to see that the data input is handled as a Matrix, had it
> > been a vector of a datatype defined as a Distance:: element, then defining
> > the application specific type (e.g. struct { point_t point; data_t data; }
> > ) and reusing the FLANN distances over "element.point" would have been the
> > way to go.
> > With the current code base, what is the recommend approach ?
> > 
> > Reply to this email directly or view it on GitHub:
> > #35

Hi @mariusmuja ,
Is this feature still valid after dynamically adding many points separately and rebuilding the index as long as we keep the addition order the same for our metadata?
