### ISSUE TITLE
Search failure in knnSearch with CUDA in VS2010

### ISSUE THREAD

**Issue by Roy0515** [mariusmuja/flann#353]
Hi guys:
           Hi, I compiled Flann1.9.1 successed  with CUDA 8.0 in VS2010 on Win7 system.
           Ant test the Flann1.9.1 with codes:

//Code start
 _#define FLANN_USE_CUDA
#include <flann/flann.hpp>

int tmpDataSize = 1000;
float* tmpData(new float[tmpDataSize*3]);

for (int iPt=0; iPt<tmpDataSize; ++iPt)
{
	tmpData[iPt*3] = iPt;
	tmpData[iPt*3 + 1] = iPt+1;
	tmpData[iPt*3 + 2] = iPt+2;
}

flann::Matrix<float> dataset(tmpData, tmpDataSize, 3);
flann::Matrix<float> query(tmpData, tmpDataSize, 3);

//Define
flann::Index<flann::L2_Simple<float> > tmpGPUIndex(dataset, flann::KDTreeCuda3dIndexParams());

//Build KdTree
tmpGPUIndex.buildIndex();

std::vector<std::vector<int> > indices;
std::vector<std::vector<float> > dists;

//K nearest Neighbor Search
tmpGPUIndex.knnSearch(query, indices, dists, 30, flann::SearchParams(-1));

printf("dists[0] size: %d\n", dists[0].size());_
//Code End

Theoretically， the project should printf:
dists[0] size: 30

Actually， it printf like that:
dists[0] size: 0

Did I miss anything?

By the way, I compiled Flann1.8.4 successed and test it like here Codes,
The test result is same as Flann1.9.1

I am lost， any help?
Thanks in advance.

**Comment by Roy0515** [comment]
More deteails, it crashes when calling buildIndex(KDTreeCuda3dIndexParams).

Any help?

**Comment by Roy0515** [comment]
Hi guys:
          A big step, hah.

Call the CUDA function like this, KDTreeCuda3dIndex will be work!


_float*_ tmpData(new float[tmpDataSize*3]);

    //...
   //set tmpData

flann::Matrix<float> dataset(tmpData, tmpDataSize, 3);
flann::Matrix<float> query(tmpData, tmpDataSize, 3);

//Note here!!!!!!!
flann::KDTreeCuda3dIndex<flann::L2_Simple<float> > tmpGPUIndex(dataset, flann::KDTreeCuda3dIndexParams());   

//Build KdTree
  tmpGPUIndex.buildIndex();   //K nearest Neighbor Search

  flann::SearchParams tmpSearchParams;
  tmpSearchParams.checks = 8;
  tmpSearchParams.sorted = false;
  tmpGPUIndex.knnSearch(query, gpu_indices, gpu_dists, tmpNN, tmpSearchParams);_

**Comment by MDurgaKeerthi** [comment]
Hi
@Roy0515  How did you compile the program?
