### ISSUE TITLE
Could NOT find tbb_debug

### ISSUE THREAD

**Issue by marusazerjal** [mariusmuja/flann#52]
Hello,
I am trying to install flann with tbb library. I installed libtbb-dev, libtbb2 and libtbb2-dbg and added the -DTBB option in CMakeLists.txt.
This is the output I get by cmake ..:

-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Warning at CMakeLists.txt:95 (message):
  gtest library not found, some tests will not be run

CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- CUDA not found, CUDA library will not be built
-- Could NOT find tbb_debug (missing:  TBB_DEBUG_LIBRARIES) 
-- Only the Intel TBB (release) libraries were found
CMake Warning at src/matlab/CMakeLists.txt:72 (message):
  Cannot find MATLAB or Octave instalation.  Make sure that the 'bin'
  directory from the MATLAB instalation or that mkoctfile is in PATH

-- Install prefix: /usr/local
-- Build type: RelWithDebInfo
-- Building C bindings: ON
-- Building python bindings: ON
-- Building matlab bindings: ON
-- Building CUDA library: OFF
-- Using MPI support: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Praline/Downloads/flann-1.7.1-src/build

TBB_DEBUG_LIBRARIES are missing and Using MPI support is OFF. Do I need to install some additional tbb libraries or is there another solution?

Thanks,
Praline

**Comment by kampta** [comment]
Is this the correct way to use it in python?
flann = Flann()
flann.build_index(X, cores = 0, algorithm="autotuned", target_precision=0.99, log_level = "info")
