### ISSUE TITLE
FLANN with LSH

### ISSUE THREAD

**Issue by CatherineY** [mariusmuja/flann#66]
Dear Marius,

I'm doing some research with ANN in hamming space. I find FLANN an excellent tool. But I'm confused how to set the parameters to realize LSH with FLANN in hamming space. Could you please provide examples of using LSH and HierarchicalClustering with hamming distances based on FLANN version 1.7.1? Thank you.

Catherine

**Comment by muyun** [comment]
Hi, Marius,
does the latest code of FLANN support the LSH and  hierarchical clustering with hamming space in C binding?  seems that I cannot find the related code piece?

Thanks in advance.
Raymond

**Comment by Natsuyu** [comment]
Woo...the test modules is so helpful !!!

**Comment by tejus-gupta** [comment]
@muyun Did you find how to use LSH and hierarchial clustering with hamming distance in C binding? If yes, can you share an example here?
